#url: https://conchoecia.github.io
#baseurl: /nccb_website/
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: nccb.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Site settings
title: NCCB
email: nccbsymposium@gmail.com
description: "The Northern California Computational Biology student group."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: 006fb8
  secondary: 00a21a
  secondary-dark: 000

# Team names, titles and social links
people:

- name: Ashley Wong
  pic: ashley
  position: speaker coordinator
  description: UCSC BMEB undergrad

- name: Akshar Lohith
  pic: akshar
  position: logistics
  description: UCSC BMEB PhD Y3
  social:
    - title: book
      url: https://www.researchgate.net/profile/Akshar_Lohith
    - title: linkedin-square
      url: https://www.linkedin.com/in/alohith/

- name: Daniel Asarnow
  pic: daniel
  position: Outreach
  description: UCSF iPQB/BP PhD Y4
  social:
    - title: github
      url: https://github.com/asarnow

- name: Matt Jones
  pic: mattjones
  position: Logistics/Website
  description: UCSF iPQB PhD Y2
  social:
    - title: github
      url: https://github.com/mattjones315
    - title: twitter
      url: https://twitter.com/mattjonesucsf

- name: Rhondene Wint
  pic: rhondene
  position: Logistics
  description: UC-Merced PhD Y2
  social:
    - title: github
      url: https://github.com/rhondene
    - title: twitter
      url: http://twitter.com/R_Winty

- name: Rinaldo Catta-Preta
  pic: rinaldo
  position: Logistics
  description: UC Davis IGG PhD Y4

- name: Diana Aguilar Gomez
  pic:
  position: 
  description: UC Berkeley

- name: Benjamin Yeh
  pic: 
  position: 
  description: Stanford

- name: Gonzalo Benegas
  pic: 
  position: 
  description: UC Berkeley

- name: Yihui Zhu
  pic: 
  position: 
  description: 

- name: Daniela Soto
  pic:
  position:
  description: 

- name: Connor Bybee
  pic: 
  position: 
  description: 

- name: Robert Stolz
  pic: 
  position: 
  description: 

- name: Megan Durham
  pic: 
  position: 
  description: 
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: facebook
      url: https://www.facebook.com/NorCalCompBio/
    - title: eventbrite
      url: https://www.eventbrite.com/e/northern-california-computational-biology-student-symposium-2017-tickets-35058505935

# Build settings
markdown: kramdown
permalink: pretty
